version: '3.4'

services: 

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./jwt.web/Dockerfile
    environment: 
      - BaseUrl=http://backend
    ports:
      - "5902:80"
    depends_on: 
      - backend
  backend:
    image: backend
    build: 
      context: .
      dockerfile: ./API/Dockerfile
    ports: 
      - "5900:80"
    command: ["dotnet", "API.dll"]