version: '3.4'

services: 

  frontend:
    image: frontend
    build:
      context: jwt.web
      dockerfile: Dockerfile
    environment: 
      - backendUrl=http://backend
    ports:
      - "5902:80"
    depends_on: 
      - backend
  backend:
    image: backend
    build: 
      context: api
      dockerfile: Dockerfile
    ports: 
      - "5900:80"
    